server:
  port: 8888
spring:
  application:
    name: nacos-consumer-openFegin
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

management:
  endpoints:
    web:
      exposure:
        include: '*'
