server:
  port: 8083
spring:
  application:
    name: nacos-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.188.101:8848

management:
  endpoint:
    web:
      exposure:
        include:'*'

# 消费者将要访问的微服务的名称
server-url:
  nacos-user-service: http://nacos-provider