server:
  port: 8084
spring:
  application:
    name: nacos-consumer
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        #??Sentinel dashboard??
        dashboard: localhost:8080
        #??8719????????????8719????+1??,???????????
        port: 8719

#??????????????(?????nacos???????)
service-url:
  nacos-user-service: http://nacos-provider